[stable2509] Bump static_init to 1.0.4 (#11720)
Fixes a bug in 1.0.3 version that does not allow code to compile due to
this error:
```
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `parking_lot`
   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/static_init-1.0.3/src/lazy_sequentializer.rs:336:13
   ```